// Core domain types for SERA AI

export interface GeneticMarker {
  rsid: string;
  gene: string;
  genotype: string;
  chromosome?: string;
  position?: number;
  note?: string;
}

export interface UserProfile {
  name?: string;
  age?: number;
  sex?: 'male' | 'female' | 'other';
  ethnicity?: string;
  medications?: string[];
  conditions?: string[];
}

export interface GeneticRule {
  id: string;
  gene: string;
  rsids: string[];
  genotypePattern: string | string[];
  category: 'drug' | 'disease' | 'lifestyle' | 'metabolic' | 'cancer';
  implication: string;
  recommendation: string;
  confidence: 'low' | 'medium' | 'high';
  evidenceUrl?: string;
  weight?: number; // For scoring
}

export interface Recommendation {
  id: string;
  ruleId: string;
  gene: string;
  rsid: string;
  category: string;
  title: string;
  explanation: string;
  patientFriendlyExplanation?: string; // Generated by Gemini
  confidence: 'low' | 'medium' | 'high';
  actions: string[];
  status: 'pending' | 'accepted' | 'declined' | 'saved';
  createdAt: number;
  geminiRefined?: boolean;
}

export interface LifestylePlanItem {
  id: string;
  title: string;
  description: string;
  frequency: 'daily' | 'weekly' | 'monthly' | 'screening';
  category: 'exercise' | 'diet' | 'medication' | 'screening' | 'lifestyle';
  completed: boolean;
  linkedRecommendationId?: string;
  dueDate?: number;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  context?: any;
}

export interface AppSettings {
  geminiApiKey?: string;
  persistApiKey: boolean;
  darkMode?: boolean;
  reducedMotion?: boolean;
}

export interface AppState {
  // User data
  userProfile: UserProfile;
  geneticMarkers: GeneticMarker[];
  recommendations: Recommendation[];
  lifestylePlan: LifestylePlanItem[];
  
  // Settings
  settings: AppSettings;
  
  // UI state
  consentGiven: boolean;
  onboardingCompleted: boolean;
  
  // Chat history
  chatHistory: ChatMessage[];
  
  // Metadata
  lastUpdated: number;
  dataVersion: string;
}

export interface GeminiConfig {
  apiKey: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
}

export interface GeminiResponse {
  text: string;
  finishReason?: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export interface GeminiStreamOptions {
  onToken?: (token: string) => void;
  onComplete?: (fullText: string) => void;
  onError?: (error: Error) => void;
}

